steps:
  # Push production image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--build-arg',
        'PUBLIC_URL=${_PUBLIC_URL}',
        '--build-arg',
        'LITERALS_FILE=${_LITERALS_FILE}',
        '--build-arg',
        'DEFAULT_WORKSPACE=${_DEFAULT_WORKSPACE}',
        '--build-arg',
        'REACT_APP_FEATURE_FLAG_SUBSCRIPTIONS=${_REACT_APP_FEATURE_FLAG_SUBSCRIPTIONS}',
        '--build-arg',
        'REACT_APP_FEATURE_TRANSLATIONS=${_REACT_APP_FEATURE_TRANSLATIONS}',
        '--build-arg',
        'REACT_APP_COMPLETE_MAP_RENDER=${_REACT_APP_COMPLETE_MAP_RENDER}',
        '--build-arg',
        'REACT_APP_DISABLE_WELCOME_MODAL=${_REACT_APP_DISABLE_WELCOME_MODAL}',
        '--build-arg',
        'REACT_APP_REQUIRE_MAP_LOGIN=${_REACT_APP_REQUIRE_MAP_LOGIN}',
        '--build-arg',
        'REACT_APP_SHOW_BANNER=${_REACT_APP_SHOW_BANNER}',
        '--build-arg',
        'REACT_APP_WELCOME_MODAL_COOKIE_KEY=${_REACT_APP_WELCOME_MODAL_COOKIE_KEY}',
        '--build-arg',
        'REACT_APP_TIMEBAR_DATA_URL=${_REACT_APP_TIMEBAR_DATA_URL}',
        '--build-arg',
        'REACT_APP_API_GATEWAY=${_REACT_APP_API_GATEWAY}',
        '--build-arg',
        'REACT_APP_SITE_URL=${_REACT_APP_SITE_URL}',
        '--build-arg',
        'REACT_APP_MAP_URL=${_REACT_APP_MAP_URL}',
        '--build-arg',
        'REACT_APP_SHARE_BASE_URL=${_REACT_APP_SHARE_BASE_URL}',
        '--build-arg',
        'REACT_APP_GOOGLE_TAG_MANAGER_KEY=${_REACT_APP_GOOGLE_TAG_MANAGER_KEY}',
        '--build-arg',
        'BASIC_AUTH_USER=$_BASIC_AUTH_USER',
        '--build-arg',
        'BASIC_AUTH_PASS=$_BASIC_AUTH_PASS',
        '--target',
        'build',
        '-t',
        'gcr.io/world-fishing-827/github.com/globalfishingwatch/map-client:$COMMIT_SHA',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'run',
        'gcr.io/world-fishing-827/github.com/globalfishingwatch/map-client:$COMMIT_SHA',
        'npm',
        'test',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--build-arg',
        'PUBLIC_URL=${_PUBLIC_URL}',
        '--build-arg',
        'LITERALS_FILE=${_LITERALS_FILE}',
        '--build-arg',
        'DEFAULT_WORKSPACE=${_DEFAULT_WORKSPACE}',
        '--build-arg',
        'REACT_APP_FEATURE_FLAG_SUBSCRIPTIONS=${_REACT_APP_FEATURE_FLAG_SUBSCRIPTIONS}',
        '--build-arg',
        'REACT_APP_FEATURE_TRANSLATIONS=${_REACT_APP_FEATURE_TRANSLATIONS}',
        '--build-arg',
        'REACT_APP_COMPLETE_MAP_RENDER=${_REACT_APP_COMPLETE_MAP_RENDER}',
        '--build-arg',
        'REACT_APP_DISABLE_WELCOME_MODAL=${_REACT_APP_DISABLE_WELCOME_MODAL}',
        '--build-arg',
        'REACT_APP_REQUIRE_MAP_LOGIN=${_REACT_APP_REQUIRE_MAP_LOGIN}',
        '--build-arg',
        'REACT_APP_SHOW_BANNER=${_REACT_APP_SHOW_BANNER}',
        '--build-arg',
        'REACT_APP_WELCOME_MODAL_COOKIE_KEY=${_REACT_APP_WELCOME_MODAL_COOKIE_KEY}',
        '--build-arg',
        'REACT_APP_TIMEBAR_DATA_URL=${_REACT_APP_TIMEBAR_DATA_URL}',
        '--build-arg',
        'REACT_APP_API_GATEWAY=${_REACT_APP_API_GATEWAY}',
        '--build-arg',
        'REACT_APP_SITE_URL=${_REACT_APP_SITE_URL}',
        '--build-arg',
        'REACT_APP_MAP_URL=${_REACT_APP_MAP_URL}',
        '--build-arg',
        'REACT_APP_SHARE_BASE_URL=${_REACT_APP_SHARE_BASE_URL}',
        '--build-arg',
        'REACT_APP_GOOGLE_TAG_MANAGER_KEY=${_REACT_APP_GOOGLE_TAG_MANAGER_KEY}',
        '--build-arg',
        'BASIC_AUTH_USER=$_BASIC_AUTH_USER',
        '--build-arg',
        'BASIC_AUTH_PASS=$_BASIC_AUTH_PASS',
        '-t',
        'gcr.io/world-fishing-827/github.com/globalfishingwatch/map-client:$COMMIT_SHA',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['push', 'gcr.io/world-fishing-827/github.com/globalfishingwatch/map-client:$COMMIT_SHA']

  # Deploy to the appropriate environment
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'beta',
        'run',
        'deploy',
        '$_RUN_SERVICE_NAME',
        '--project',
        '$_RUN_PROJECT',
        '--image',
        'gcr.io/world-fishing-827/github.com/globalfishingwatch/map-client:$COMMIT_SHA',
        '--region',
        '$_RUN_REGION',
        '--platform',
        'managed',
        '--set-env-vars',
        'BASIC_AUTH=$_BASIC_AUTH',
        '--allow-unauthenticated',
      ]

images:
  - 'gcr.io/world-fishing-827/github.com/globalfishingwatch/map-client:$COMMIT_SHA'
